### ISSUE TITLE
make test throws a WebpackOptionsValidationError

### ISSUE THREAD

**Issue by wilfred-s** [cloudera/yunikorn-web#14]
While working on the consistency in the Makefiles I ran into some issues with `make test`. Most issues were simple to solve and were related to running test after calling `make clean` 

The following failure still happens directly after we start the `ng test` (the first test step). This is reproducible when calling `ng test` outside of make:
```
ng test
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'futureEmitAssets'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, webassemblyModuleFilename?, globalObject?, crossOriginLoading?, jsonpScriptType?, chunkLoadTimeout?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, devtoolNamespace?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, chunkCallbackName?, library?, libraryTarget?, libraryExport?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
    at webpack (/Users/wilfred/repos/yunikorn/src/github.com/cloudera/yunikorn-web/node_modules/webpack/lib/webpack.js:24:9)
    at init (/Users/wilfred/repos/yunikorn/src/github.com/cloudera/yunikorn-web/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts:150:16)
    at Array.invoke (/Users/wilfred/repos/angular/angular-cli/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/wilfred/repos/angular/angular-cli/node_modules/di/lib/injector.js:48:43)
    at config.frameworks.forEach (/Users/wilfred/repos/angular/angular-cli/node_modules/karma/lib/server.js:159:61)
    at Array.forEach (<anonymous>)
    at Server._start (/Users/wilfred/repos/angular/angular-cli/node_modules/karma/lib/server.js:159:23)
    at Injector.invoke (/Users/wilfred/repos/angular/angular-cli/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/wilfred/repos/angular/angular-cli/node_modules/karma/lib/server.js:133:22)
29 08 2019 15:01:42.180:ERROR [karma-server]: Server start failed on port 9876: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'futureEmitAssets'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, webassemblyModuleFilename?, globalObject?, crossOriginLoading?, jsonpScriptType?, chunkLoadTimeout?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, devtoolNamespace?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, chunkCallbackName?, library?, libraryTarget?, libraryExport?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
make: *** [test] Interrupt: 2
```

**Comment by wilfred-s** [comment]
This issue is resolved as part of the angular changes
fixed by #21
